# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CoordinateSelectUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CoordinateSelect_Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.setWindowModality(QtCore.Qt.WindowModal)
        dialog.setEnabled(True)
        dialog.resize(375, 208)
        self.buttonBox = QtWidgets.QDialogButtonBox(dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(dialog)
        self.widget.setGeometry(QtCore.QRect(30, 50, 241, 52))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_Start_x = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Start_x.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Start_x.setObjectName("lineEdit_Start_x")
        self.horizontalLayout.addWidget(self.lineEdit_Start_x)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_Start_y = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Start_y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Start_y.setObjectName("lineEdit_Start_y")
        self.horizontalLayout.addWidget(self.lineEdit_Start_y)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_End_x = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_End_x.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_End_x.setObjectName("lineEdit_End_x")
        self.horizontalLayout_2.addWidget(self.lineEdit_End_x)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_End_y = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_End_y.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_End_y.setObjectName("lineEdit_End_y")
        self.horizontalLayout_2.addWidget(self.lineEdit_End_y)
        self.verticalLayout.addLayout(self.horizontalLayout_2)


        self.retranslateUi(dialog)
        self.buttonBox.accepted.connect(dialog.accept)
        self.buttonBox.rejected.connect(dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "矩形框选择"))
        self.label.setText(_translate("dialog", "起始坐标："))
        self.label_3.setText(_translate("dialog", "x:"))
        self.label_4.setText(_translate("dialog", "y:"))
        self.label_2.setText(_translate("dialog", "终点坐标："))
        self.label_5.setText(_translate("dialog", "x:"))
        self.label_6.setText(_translate("dialog", "y:"))
