# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GraphicViewTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ImgView = QtWidgets.QGraphicsView(self.centralwidget)
        self.ImgView.setGeometry(QtCore.QRect(20, 90, 421, 401))
        self.ImgView.setObjectName("ImgView")
        self.BinaryImgView = QtWidgets.QGraphicsView(self.centralwidget)
        self.BinaryImgView.setGeometry(QtCore.QRect(470, 90, 421, 401))
        self.BinaryImgView.setObjectName("BinaryImgView")
        self.button_Amplify = QtWidgets.QPushButton(self.centralwidget)
        self.button_Amplify.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.button_Amplify.setObjectName("button_Amplify")
        self.button_lessen = QtWidgets.QPushButton(self.centralwidget)
        self.button_lessen.setGeometry(QtCore.QRect(160, 50, 75, 23))
        self.button_lessen.setObjectName("button_lessen")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_Amplify.setText(_translate("MainWindow", "放大"))
        self.button_lessen.setText(_translate("MainWindow", "缩小"))
